### ISSUE TITLE
Ошибка при выполнении тестов о несовместимости версий

### ISSUE THREAD

**Issue by romhaberman** [romhaberman/BDD#1]
После выполнения теста появляется сообщение об ошибке: "В этой сборке были использованы устаревшие функции Gradle, что делает ее несовместимой с Gradle 9.0."

![IDEA error](https://github.com/user-attachments/assets/b0741119-8d9e-4e13-a324-4450c9856e91)

В репозитории reports/tests/test... ошибка: "Невозможно найти реализацию CDP, соответствующую 128"

![reports-tests-test-index](https://github.com/user-attachments/assets/ee80e38e-96b7-41d7-92c6-f0161dea99b4)

**Comment by andrew-pahomov** [comment]
Добрый день        

Думаю в первую очередь надо обратить внимание на IllegalArgumentException в 35 строке MoneyTransferTest. В этом причина падения теста на скрине, а не в информационных сообщениях о версиях.
