### ISSUE TITLE
Ошибка об отсутствии сообщении об ошибке

### ISSUE THREAD

**Issue by romhaberman** [romhaberman/BDD#3]
Тест не проходит, сообщение что не найден ожидаемый текст об ошибке

![ошибка 30-08-2024](https://github.com/user-attachments/assets/fb841554-a38d-4c48-8a53-8503d5def801)
---
![IDEA ошибка 30-08-2024](https://github.com/user-attachments/assets/a57fed30-96af-4686-87fd-098a54d0308e)

**Comment by andrew-pahomov** [comment]
Думаю вам в первую очередь стоит хорошо обдумать сценарий падающего теста и понять должно ли отображаться сообщение об ошибке. Возможно ваш тест имеет правильный ожидаемый результати проблема в тестирумом приложении.
